### ISSUE TITLE
routeFolder

### ISSUE THREAD

**Issue by L1lith** [Talha-T/neistion#11]
The routerFolder in the Neiston options will automatically deeply require all files in that folder and their outputs will be treated as routes. This way you can cleanly organize all of your routes without needing to create a huge array of require statements. I recommend [Require Directory](https://www.npmjs.com/package/require-directory) for this, and you can create behavior with this where the folder names are treated as part of the path.

**Comment by L1lith** [comment]
Here's an example of my current server directory structure
<img width="169" alt="screen shot 2018-08-29 at 12 09 45 pm" src="https://user-images.githubusercontent.com/34887287/44806534-74e50900-ab84-11e8-877d-a64ceb56f34d.png">

**Comment by L1lith** [comment]
I think I will make this into it's own package and you can just implement it if you want to.

**Comment by Talha-T** [comment]
Thanks, I will appreciate it.
