### ISSUE TITLE
Verify Function Accept Callback

### ISSUE THREAD

**Issue by L1lith** [Talha-T/neistion#9]
The verify function should also provide a "authorized" callback like this, because sometimes you will be forcing users to make their code by wrapping their code that only works with callbacks into a promise constructor.
```js
verify: authorized => setTimeout(authorized, 1000)
```

**Comment by Talha-T** [comment]
verify is async too(optional)

**Comment by L1lith** [comment]
Yeah, but sometimes it doesn't make sense to use promises instead of callbacks. Some libraries don't support it and some native JS functions use callbacks.

**Comment by Talha-T** [comment]
Okay then

**Comment by Talha-T** [comment]
Fixed with f861a8b
